version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ISFT
    restart: always
    ports:
      - ${APACHE_ISFT_PORT}:80
    env_file: .env
    volumes:
      - ./web:/var/www/html
    networks: 
      - network1
networks: 
  network1: 
    external: 
      name: ${RED_NOW}
