version: '3.3'
services:
  web:
    build: 
     context: .
     dockerfile: Dockerfile
    env_file:
      - .env
    volumes: 
      - ./web:/var/www/html
    ports:
      - ${APACHE_ISFT_PORT}:80
    container_name: ISFT
    restart: always
    networks: 
      - network1
    environment:
      - PHP_IP_ADDRESS=${PHP_IP_ADDRESS}

networks: 
  network1: 
    external: 
      name: ${RED_NOW}
